export { default as Splash } from './Splash/Splash';
export { default as Splash2 } from './Splash/Splash2';
export { default as Login } from './Login/Login';
export { default as LoginOtp } from './LoginOtp/LoginOtp';
export { default as Signup } from './Signup/Signup';
export { default as ForgotPassword } from './ForgotPassword/ForgotPassword';
export { default as Home } from './Home/Home';
export { default as Dashboard } from './Dashboard/Dashboard';
export { default as Profile } from './Profile/Profile';